project:
  type: website
  output-dir: docs
lang: en

website:
  title: "Corentin Maslard"
  favicon: media/growing-plant.png
  navbar:
    left:
      - href: index.qmd
        text: " "
      - href: me.qmd
      - href: tools.qmd
      - href: publications.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    toc: false