project:
  type: website
  output-dir: docs
lang: en

website:
  title: "Corentin Maslard"
  navbar:
    left:
      - href: index.qmd
        text: " "
      - href: me.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false